

device: "cuda:0"
seed: 42

lr: 3e-4
weight_decay: 1e-4

betas: [0.9, 0.999]
eps: 1e-8

warmup_ratio: 0.05
wand_project: 'rvm-action-recog'
checkpoints_dir: 'checkpoints_ssv2_acr'
restored_params_path: '/home/geometric-ssl/src/evals/ckpts/pretrain_rvm_small16_256_204031069.npz'