_wandb:
    value:
        cli_version: 0.28.1
        e:
            ptx7ms8hudo6kyolagpgjmv0kl0tatyg:
                args:
                    - --config
                    - training_config.yaml
                codePath: evals/action_recog/trainer_rvm_dino.py
                codePathLocal: trainer_rvm_dino.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "942211411968"
                        used: "333410111488"
                email: maheshreddy0299@gmail.com
                executable: /root/miniconda3/envs/gssl/bin/python3
                git:
                    commit: 106cd6532362f86a739c59d627864c4292a353b8
                    remote: https://github.com/maheshreddy24/rvm.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-7dc367a4-f251-5af8-0502-da33005a8749
                host: e506572871b6
                memory:
                    total: "1081751564288"
                os: Linux-6.8.0-100-generic-x86_64-with-glibc2.35
                program: /home/rvm/evals/action_recog/trainer_rvm_dino.py
                python: CPython 3.10.20
                root: /home/rvm/evals/action_recog
                startedAt: "2026-08-07T07:00:20.793100Z"
                writerId: ptx7ms8hudo6kyolagpgjmv0kl0tatyg
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.20
            "5": 0.28.1
            "6": 5.14.1
            "12": 0.28.1
            "13": linux-x86_64
amp:
    value: true
batch_size:
    value: 32
betas:
    value:
        - 0.9
        - 0.999
checkpoint_dir:
    value: frozen_dino_backbone
dataset_config_path:
    value: /home/rvm/evals/action_recog/dataset_config.yaml
device:
    value: cuda:0
eps:
    value: 1e-08
eval_interval:
    value: 1000
log_interval:
    value: 200
lr:
    value: 0.0003
min_lr:
    value: 1e-07
num_epochs:
    value: 2
num_workers:
    value: 16
readout_dim:
    value: 768
readout_in_dim:
    value: 384
readout_num_classes:
    value: 174
readout_num_heads:
    value: 12
restored_params_path:
    value: /home/rvm/rvm_ckpts/pretrain_rvm_small16_256_204031069.npz
rvm_weights_path:
    value: /home/rvm/checkpoints_ema_dino_backbone/exp_1786079519.802173/model_epoch2_step4000.pth
seed:
    value: 42
wandb_name:
    value: ssv2-readout-run1
wandb_project:
    value: rvm-action-recog
warmup_ratio:
    value: 0.05
weight_decay:
    value: 0.0001
